# Generated by Django 3.0.5 on 2020-05-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=255, unique=True, verbose_name='アカウント名')),
                ('username', models.CharField(max_length=255, verbose_name='ユーザー名')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='プロフィール画像')),
            ],
        ),
    ]
