# Generated by Django 3.0.5 on 2020-05-05 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200504_1359'),
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='liked_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_users', to='user.User'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user', to='user.User'),
        ),
    ]
