# Generated by Django 3.0.5 on 2020-05-06 09:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200504_1359'),
        ('tweet', '0002_auto_20200505_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 6, 9, 12, 53, 219955), verbose_name='現在の時刻'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=140, verbose_name='コメント')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 5, 6, 9, 12, 53, 220937), verbose_name='現在の時刻')),
                ('tweet_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tweet.Tweet')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.User')),
            ],
        ),
    ]
